/**
 * Test pdf-parse on a buffer generated by pdf-parse's own test suite approach.
 * Also test mammoth (DOCX) extraction separately.
 */
const pdfParse = require('pdf-parse');
const fs = require('fs');

async function test() {
    // pdf-parse includes its own test PDF — let's find it
    const testPdfPath = require.resolve('pdf-parse/test/data/05-versions-space.pdf');
    console.log('Using pdf-parse test PDF:', testPdfPath);

    const buffer = fs.readFileSync(testPdfPath);
    console.log('Buffer size:', buffer.length, 'bytes');

    try {
        const data = await pdfParse(buffer);
        console.log('\n=== PDF EXTRACTION RESULT ===');
        console.log('Pages:', data.numpages);
        console.log('Text length:', data.text.length, 'characters');
        console.log('Text preview:', data.text.substring(0, 300));
        console.log('\nSUCCESS - pdf-parse works correctly with buffers!');
    } catch (err) {
        console.log('FAILED:', err.message);
    }
}

test().catch(e => console.error('Error:', e));
